<?php

namespace AppBundle\Repository;

/**
 * accessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class accessRepository extends \Doctrine\ORM\EntityRepository
{
}
