<?php

namespace AppBundle\Repository;

/**
 * File_downloadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class File_downloadRepository extends \Doctrine\ORM\EntityRepository
{
}
