<?php

namespace AppBundle\Repository;

/**
 * File_adddRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class File_adddRepository extends \Doctrine\ORM\EntityRepository
{
}
