app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_login:
    path: /login

_register:
    path: /register

_home:
    path: /

_upload:
    path: /product/new

_count:
    path: /count

_main:
    path: /main
    defaults: { _controller: AppBundle:Main:index }

app_course:
    resource: "@AppBundle/Resources/config/routing/course.yml"
    prefix: /course

app_file:
    resource: "@AppBundle/Resources/config/routing/file.yml"
    prefix: /file

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /user
