access_index:
    path:     /
    defaults: { _controller: "AppBundle:access:index" }
    methods:  GET

access_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:access:show" }
    methods:  GET

access_new:
    path:     /new
    defaults: { _controller: "AppBundle:access:new" }
    methods:  [GET, POST]

access_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:access:edit" }
    methods:  [GET, POST]

access_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:access:delete" }
    methods:  DELETE
