file_addd_index:
    path:     /
    defaults: { _controller: "AppBundle:File_addd:index" }
    methods:  GET

file_addd_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:File_addd:show" }
    methods:  GET

file_addd_new:
    path:     /new
    defaults: { _controller: "AppBundle:File_addd:new" }
    methods:  [GET, POST]

file_addd_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:File_addd:edit" }
    methods:  [GET, POST]

file_addd_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:File_addd:delete" }
    methods:  DELETE
