AppBundle\Entity\File_download:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\File_downloadRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dataAdd:
            type: datetime
            column: data_add
        courseNr:
            type: integer
            column: course_nr
        fileNr:
            type: integer
            column: file_nr
        userNr:
            type: string
            length: 255
            column: user_nr
    lifecycleCallbacks: {  }
