AppBundle\Entity\File_addd:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\File_adddRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateAdd:
            type: datetime
            column: date_add
        courseNr:
            type: integer
            column: course_nr
        userNr:
            type: integer
            column: user_nr
        fileNr:
            type: integer
            column: file_nr
    lifecycleCallbacks: {  }
