AppBundle\Entity\Lecture:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\LectureRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            column: Title
        created:
            type: datetime
        course:
            type: string
            length: 255
    lifecycleCallbacks: {  }
